search: search.c
	clang search.c -lcs50 -o search -Wl,-rpath,/usr/local/lib
phonebook: phonebook.c
	clang phonebook.c -lcs50 -o phonebook -Wl,-rpath,usr/local/lib
iteration: iteration.c
	clang iteration.c -lcs50 -o iteration -Wl,-rpath,usr/local/lib
recursion: recursion.c
	clang recursion.c -lcs50 -o recursion -Wl,-rpath,usr/local/lib